apiVersion: v1
data:
  zoo.cfg: |
    tickTime=2000
    dataDir=/var/lib/zookeeper/data
    dataLogDir=/var/lib/zookeeper/log
    clientPort=2181
    initLimit=5
    syncLimit=20
    minSessionTimeout= 4000
    maxSessionTimeout= 40000
    server.1=zk-0.zk-headless.default.svc.cluster.local:2888:3888
    server.2=zk-1.zk-headless.default.svc.cluster.local:2888:3888
    server.3=zk-2.zk-headless.default.svc.cluster.local:2888:3888
kind: ConfigMap
metadata:
  name: zoo-configmap
