#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mysql
#  labels:
#    app: mysql-demo
#spec:
#  ports:
#  - port: 3306
#    name: server
#  clusterIP: None
#  selector:
#    app: mysql
#---

apiVersion: v1
kind: Pod
metadata:
  name: mysql-demo
spec:
  containers:
    - name: mysql-demo
      image: mysql:5.6
      imagePullPolicy: Always
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "123456"

#volumeClaimTemplates:
#  - metadata:
#      name: datadir
#      annotations:
#        volume.beta.kubernetes.io/storage-class: anything
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      resources:
#        requests:
#          storage: 3Gi