---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  externalIPs:
    - 192.168.225.137
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql-demo
---
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
      app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-demo
        image: mysql:5.6
        imagePullPolicy: Always
        env:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "123456"
        ports:
          - containerPort: 3306
            name: server
        volumeMounts:
          - name: datadir
            mountPath: /var/lib/mysql
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: mysql-pvc
---