apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
      app: mysql-persistentVolume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/data/mysql
    server: 192.168.225.137