apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
      app: mysql-persistentVolume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/data/mysql
    server: 192.168.225.137

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zoo-pv0001
  labels:
      app: zoo-persistentVolume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/data/zoo1
    server: 192.168.225.137

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zoo-pv0002
  labels:
      app: zoo-persistentVolume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/data/zoo2
    server: 192.168.225.137

apiVersion: v1
kind: PersistentVolume
metadata:
  name: zoo-pv0003
  labels:
      app: zoo-persistentVolume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfs/data/zoo3
    server: 192.168.225.137